#version 460
layout(local_size_x=8, local_size_y=8, local_size_z=1) in;
layout(binding=0, rgba8) uniform writeonly image2D outImg;
layout(push_constant) uniform PC{float t; float pad0; float pad1; float pad2;};
void main(){ivec2 p=ivec2(gl_GlobalInvocationID.xy);
  vec2 uv=(vec2(p)+0.5)/vec2(imageSize(outImg));
  float v=0.5+0.5*sin(10.0*uv.x+6.0*uv.y+ t*2.0);
  vec3 c=mix(vec3(0.1,0.2,0.8),vec3(0.9,0.8,0.2),v);
  imageStore(outImg,p,vec4(c,1.0));}

