name: windows-build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1
        with:
          vulkan_version: 1.4.321.1
          install_runtime: false
          cache: true

      - name: Verify Vulkan tools
        run: |
          echo "VULKAN_SDK=$env:VULKAN_SDK"
            if (-not (Test-Path "$env:VULKAN_SDK\Bin\glslc.exe")) { Write-Error 'glslc not found'; exit 1 }
          & "$env:VULKAN_SDK\Bin\glslc.exe" --version
          if (Get-Command vulkaninfo -ErrorAction SilentlyContinue) {
            vulkaninfo | Select-String -Pattern 'Vulkan Instance Version'
          } else {
            Write-Warning 'vulkaninfo not in PATH (some minimal installs omit it)';
          }
        shell: powershell

      - name: Configure (Release)
        run: |
          cmake -S . -B build -DVULKAN_VISUALIZER_BUILD_EXAMPLE=ON -DCMAKE_BUILD_TYPE=Release
        shell: powershell

      - name: Build (library + examples)
        run: |
          cmake --build build --config Release --parallel
        shell: powershell

      - name: Package artifacts
        if: success()
        run: |
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          if (Test-Path build/examples/Release/basic_window.exe) { Copy-Item build/examples/Release/basic_window.exe artifacts/ -Force }
          if (Test-Path build/examples/Release/SDL3.dll) { Copy-Item build/examples/Release/SDL3.dll artifacts/ }
          if (Test-Path build/Release/vulkan_visualizer.lib) { Copy-Item build/Release/vulkan_visualizer.lib artifacts/ }
          if (Test-Path build/Release/vulkan_visualizer.pdb) { Copy-Item build/Release/vulkan_visualizer.pdb artifacts/ }
        shell: powershell

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-output
          path: artifacts
          if-no-files-found: error

      - name: (Optional) Shader compile smoke check
        if: success()
        run: |
          if (Test-Path build/examples/shaders) { Get-ChildItem build/examples/shaders } else { echo 'Shader dir missing (was glslc skipped?)' }
        shell: powershell
